// <auto-generated />
namespace Hastane_yazilimi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Hastane2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hastane2));
        
        string IMigrationMetadata.Id
        {
            get { return "202205171317191_Hastane2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
